# Generated by Django 2.0.6 on 2018-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default='nyuFQZYV1KjrB1cnjlxz55jLbbBzY9dp', max_length=32),
        ),
    ]
