# Generated by Django 2.0.6 on 2018-08-24 05:06

from django.db import migrations, models
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=user.models.user.make_secret_key, max_length=32),
        ),
    ]
