language: python
python:
  - "3.6"
before_install:
  - cd src
install:
  - pip install -r requirements.dev.txt
script:
  - coverage run --source='.' manage.py test
  - coverage report
  - codecov
  - pylint --load-plugins pylint_django */