language: python
services:
  - postgresql
python:
  - "3.6"
before_install:
  - cd src
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - pip install -r requirements.dev.txt
script:
  - env DATABASE_URL=pgsql://postgres@localhost/travis_ci_test coverage run --source='.' manage.py test
  - coverage report
  - codecov
  - pylint --load-plugins pylint_django */
