# Generated by Django 2.0.6 on 2018-08-25 01:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20180824_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='model',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
