# Generated by Django 2.0.6 on 2018-08-28 02:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_pipeline_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('addr', models.URLField(max_length=255)),
                ('alive', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
